services:
  database:
    container_name: database-casino
    build: 
      context: "./db"
    environment:
      - POSTGRES_USER=${DB_USER:-casino}
      - POSTGRES_PASSWORD=${DB_PASS:-casino}
      - POSTGRES_DB=casino_db  
    networks: 
      - casino-net
    ports:
      - "5432:5432"    
    volumes:
      - pg-data:/var/lib/postgresql/data


  back:
    container_name: backend-casino
    
    build: 
      context: "."


    environment:
      - DB_HOST=database 
      - DB_USER=${DB_USER:-casino} 
      - DB_PASSWORD${DB_PASS:-casino} 
      - DB_NAME=casino_db
      - JWT_SECRET=${JWT_SECRET:-dev}
      - CORS_ORIGIN="*"
    networks: 
      - casino-net
    ports:
      - "3000:3000"    

  front:
    
    container_name: frontend-casino
    build: 
      context: "../frontend_intro_devops_casino"    
    
    environment:
      - BACKEND_HOST=back
    networks: 
      - casino-net
    ports:
      - "8000:80"


volumes:
  pg-data:


networks:
  casino-net:
    driver: "bridge"
