services:
  database:
    container_name: database-casino
    build: 
      context: "./db"
    environment:
      - POSTGRES_USER=${DB_USER:-casino}
      - POSTGRES_PASSWORD=${DB_PASS:-casino}
      - POSTGRES_DB=casino_db  
    networks: 
      - casino-net
    ports:
      - "5432:5432"    
    volumes:
      - pg-data:/var/lib/postgresql/data


  back:
    container_name: backend-casino
    
    build: 
      context: "."

    environment:
      - DB_HOST=database 
      - DB_USER=${DB_USER:-casino} 
      - DB_PASSWORD${DB_PASS:-casino} 
      - DB_NAME=casino_db
      - JWT_SECRET=${JWT_SECRET:-dev}
      - CORS_ORIGIN="*"
    networks: 
      - casino-net
    ports:
      - "8000:3000"    

  estadisticas:
    container_name: estadisticas-service
    
    build: 
      context: "../estadisticas-service"

    environment:
      - DB_HOST=database 
      - DB_USER=${DB_USER:-casino} 
      - DB_PASSWORD${DB_PASS:-casino} 
      - DB_NAME=casino_db
      - JWT_SECRET=${JWT_SECRET:-dev}
      - CORS_ORIGIN="*"
    networks: 
      - casino-net
    ports:
      - "8002:3002"    

  bonos:
    container_name: bonos-service
    
    build: 
      context: "../bonos-service"

    environment:
      - DB_HOST=database 
      - DB_USER=${DB_USER:-casino} 
      - DB_PASSWORD${DB_PASS:-casino} 
      - DB_NAME=casino_db
      - JWT_SECRET=${JWT_SECRET:-dev}
      - CORS_ORIGIN="*"
    networks: 
      - casino-net
    ports:
      - "8001:3001"    

  apuestas:
    container_name: apuestas-service
    
    build: 
      context: "../apuestas-service"

    environment:
      - DB_HOST=database 
      - DB_USER=${DB_USER:-casino} 
      - DB_PASSWORD${DB_PASS:-casino} 
      - DB_NAME=casino_db
      - JWT_SECRET=${JWT_SECRET:-dev}
      - CORS_ORIGIN="*"
    networks: 
      - casino-net
    ports:
      - "8003:3003"    


  front:    
    container_name: frontend-casino
    build: 
      context: "../frontend_intro_devops_casino"    
    
    environment:
      - BACKEND_HOST=back
      - BONOS_HOST=bonos
      - APUESTAS_HOST=apuestas
      - ESTADISTICAS_HOST=estadisticas
      
    networks: 
      - casino-net
    ports:
      - "7000:80"


volumes:
  pg-data:


networks:
  casino-net:
    driver: "bridge"
