apiVersion: v1
kind: Service
metadata:
  name: casino-backend
  labels:
    app: casino-backend
spec:
  # ClusterIP = solo accesible DENTRO del clúster.
  # Otros servicios lo alcanzan vía DNS interno: http://products-service:8001
  type: ClusterIP
  selector:
    app: casino-backend
  ports:
    - name: back-ext
      protocol: TCP
      port: 3000       # puerto del Service (DNS interno)
      targetPort: 3000  # puerto del contenedor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: casino-backend
  labels:
    app: casino-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: casino-backend
  template:
    metadata:
      labels:
        app: casino-backend
    spec:
      containers:
        - name: casino-backend
          image: <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/casino-backend:latest
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /livez
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"


          env:
            - name: DB_HOST
              value: casino-db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: casino-secrets
                  key: POSTGRES_USER
                  
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: casino-secrets
                  key: POSTGRES_PASSWORD
                  
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: casino-secrets
                  key: POSTGRES_DB
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: casino-secrets
                  key: JWT_SECRET
