apiVersion: v1
kind: Service

metadata:
  name: casino-db
  labels:
    app: casino-db


spec:
  type: ClusterIP
  selector:
    app: casino-db
  ports:
    - name: postgres
      protocol: TCP
      port: 5432        # puerto del Service (DNS interno)
      targetPort: 5432  # puerto del contenedor

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: casino-db
  labels:
    app: casino-db

spec:
  serviceName: "casino-db"
  replicas: 1
  selector:
    matchLabels:
      app: casino-db
  template:
    metadata:
      labels:
        app: casino-db
    spec:
      terminationGracePeriodSeconds: 15


      containers:
      
        - name: casino-db
          image: <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/casino-db:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: casino-secrets
                  key: POSTGRES_USER
                  
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: casino-secrets
                  key: POSTGRES_PASSWORD
                  
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: casino-secrets
                  key: POSTGRES_DB

          resources:
            requests:
              cpu: "128m"
              memory: "64Mi"
            limits:
              memory: "256Mi"
              cpu: "500m"
              
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "$(POSTGRES_USER)", "-d", "$(POSTGRES_DB)"]
            periodSeconds: 10
            initialDelaySeconds: 10
