apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-persist
  namespace: default
spec:
  volumeName: pg-persist
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Gi
