apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-static
  namespace: default
spec:
  volumeName: pg-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: 'gp3'