apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com # Requires the AWS EBS CSI Driver installed
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  volumeMode: Filesystem # Explicitly requests a mounted directory system (Default)
  resources:
    requests:
      storage: 2Gi
---