apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: casino-db
  labels:
    app: casino-db

spec:
  serviceName: "casino-db"
  replicas: 1
  selector:
    matchLabels:
      app: casino-db
  template:
    metadata:
      labels:
        app: casino-db
    spec:
      terminationGracePeriodSeconds: 15


      containers:
      
        - name: casino-db
          image: <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/casino-db:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "casino"
            - name: POSTGRES_PASSWORD
              value: "casino"
            - name: POSTGRES_DB
              value: "casino_db"


          volumeMounts:                 
            - name: pg-storage
              mountPath: /var/lib/postgresql/data   

          resources:
            requests:
              cpu: "128m"
              memory: "64Mi"
            limits:
              memory: "256Mi"
              cpu: "500m"
              
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "$(POSTGRES_USER)", "-d", "$(POSTGRES_DB)"]
            periodSeconds: 10
            initialDelaySeconds: 10

          # 3. Liveness Probe: Triggers a container restart if the database locks up entirely
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "$(POSTGRES_USER)", "-d", "$(POSTGRES_DB)"]
            initialDelaySeconds: 30
            periodSeconds: 10
  
      volumes:
        - name: pg-storage
          persistentVolumeClaim:
            claimName: pg-storage