apiVersion: apps/v1
kind: Deployment
metadata:
  name: casino-db
  labels:
    app: casino-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: casino-db
  template:
    metadata:
      labels:
        app: casino-db
    spec:
      volumes:
        - name: "pg-data"
          hostPath:
            path: "/Users/user/Documents/docker/osdsk8s/pg-data"
            type: Directory



      containers:
        - name: casino-db
          image: <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/casino-db:latest
          ports:
            - containerPort: 5432

          # here because faster and easier for quickness, maybe i'll properly secret them later
          # i don't know if k8s supports this ${DB_PASS:-casino} type of formatting
          env:
            - name: POSTGRES_USER
              value: "casino"
            - name: POSTGRES_PASSWORD
              value: "casino"
            - name: POSTGRES_DB
              value: "casino_db"



          volumeMounts:                 
            - name: pg-data
              mountPath: /var/lib/postgresql/data   

          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
