apiVersion: v1
kind: Service

metadata:
  name: casino-db
  labels:
    app: casino-db


spec:
  type: ClusterIP
  selector:
    app: casino-db
  ports:
    - name: postgres
      protocol: TCP
      port: 5432        # puerto del Service (DNS interno)
      targetPort: 5432  # puerto del contenedor
