name: Build & Deploy database

on:
  workflow_dispatch:
  push:
    branches: [ deploy ]
    paths: [ 'db/**', '.github/workflows/deploy-db.yml' ]


env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: microservicios-casino

jobs:
  buildPush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar credenciales AWS (temporales del Learner Lab)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Login a ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Debugging ls
        run: ls -la

      - name: Build & Push to ECR
        env:
          REGISTRY: ${{ steps.ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
            docker build -t "$REGISTRY/casino-db:$IMAGE_TAG" -t "$REGISTRY/casino-db:latest" "db/"
            docker push "$REGISTRY/casino-db:$IMAGE_TAG"
            docker push "$REGISTRY/casino-db:latest"
          
          
  k8sDeploy:
    runs-on: ubuntu-latest
    needs: buildPush
    steps:
      - name: "i don't know how not to have to checkout again."
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS (temporales del Learner Lab)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Login a ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2
        
      - name: Instalar kubectl en el runner
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/kubectl

      - name: Conectar kubectl al cluster
        run: aws eks update-kubeconfig --name "$CLUSTER_NAME" --region "$AWS_REGION"
      - name: Debugging ls
        run: ls -la

      - name: Desplegar la BD
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
            sed -i "s|<ACCOUNT_ID>|$ACCOUNT_ID|g; s|<REGION>|$AWS_REGION|g; s|:latest|:$IMAGE_TAG|g" "k8s/deployment.yaml"
            kubectl apply -f "db/k8s/dbclaim.yaml"
            kubectl apply -f "db/k8s/deployment.yaml"
            kubectl apply -f "db/k8s/service.yaml"
         
      - name: Esperar al rollout
        run: |
          kubectl rollout status statefulset/casino-db --timeout=180s
          kubectl get pods -o wide
